stages:
  - build
  - test
  - deploy

include:
  - local: .gitlab/vars/dependency-proxy.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE == "Taucher2003-Group"

variables:
  MAVEN_IMAGE: ${PROXY_PREFIX}maven:3.8.4-openjdk

default:
  image: $MAVEN_IMAGE
  cache:
    when: on_success
    paths:
      - '**/target'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit:
        - '**/target/surefire-reports/TEST-*.xml'

deploy:
  stage: deploy
  script:
    - echo TODO
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH